language: dart
sudo: false
dart:
  - stable
  - dev

dart_task:
  - test: -p vm -x aot --timeout 4x
    xvfb: false
  - test: test/test_on_travis.dart
    install_dartium: true
  - dartfmt
  # Let's be super aggressive, since it's 100% at the moment
  - dartanalyzer: . --fatal-hints --fatal-warnings --fatal-lints

matrix:
  allow_failures:
    - dart: dev

cache:
  directories:
    - $HOME/.pub-cache

branches:
  only: [master]
