name: angular_test
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular_testing
description: Testing infrastructure for AngularDart
version: 0.1.0-dev

environment:
  sdk: '>=1.20.0 <2.0.0'

executables:
  angular_testing: test

dependencies:
  angular2:
  ansicolor:

dev_dependencies:
  dart_style:
  test: '^0.12.17'

transformers:
  # Run the code generator on the entire package.
  - angular2/transform/codegen

  # Run the reflection remover just on tests that have AoT enabled.
  # TODO: Automate this, either via script or a naming convention.
  - angular2/transform/reflection_remover:
      $include:
          - test/frontend/bed_error_test.dart
          - test/bootstrap_test.dart

  # Allow test to proxy-load files so we can run AoT tests w/ pub serve.
  - test/pub_serve:
      $include: test/**_test.dart